name: Docker Build and Save
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t Dockerfile:latest .
      
      - name: Save Docker image
        run: docker save -o Dockerfile.tar my-image:latest
      
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-image
          path: my-image.tar
